spring.application.name=track-my-vehicle-backend

server.servlet.context-path=/track-my-vehicle
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/track-my-vehicle-db
spring.datasource.username=${username}
spring.datasource.password=${password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.properties.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


# osm config
app.osm.base-url=https://nominatim.openstreetmap.org

app.osrm.base-url=http://router.project-osrm.org
app.osrm.service=route
app.osrm.version=v1
app.osrm.profile=driving